import type { Platform } from "./types.js";

export interface GuiBootState {
  platforms: Platform[];
  browserAutomationEnabled: boolean;
  ebayDefaults: {
    sku: string;
    merchantLocationKey: string;
    fulfillmentPolicyId: string;
    paymentPolicyId: string;
    returnPolicyId: string;
  };
}

function escapeJsonForScript(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}

export function buildGuiScript(boot: GuiBootState): string {
  const lines: string[] = [
    `const BOOT = ${escapeJsonForScript(boot)};`,
    "const state = { draftId: null, draft: null, localPreviewUrls: [], serverPreviewUrls: [], publishResults: [], saveTimer: null };",
    "const els = {",
    "  form: document.getElementById('draft-form'),",
    "  photoInput: document.getElementById('photos'),",
    "  noteInput: document.getElementById('notes'),",
    "  platformInputs: Array.from(document.querySelectorAll('input[name=\"platforms\"]')),",
    "  buildButton: document.getElementById('build-draft'),",
    "  publishButton: document.getElementById('publish-all'),",
    "  status: document.getElementById('global-status'),",
    "  summary: document.getElementById('summary'),",
    "  photoPreview: document.getElementById('photo-preview'),",
    "  listingCards: document.getElementById('listing-cards'),",
    "  publishPanel: document.getElementById('publish-panel'),",
    "  resultPanel: document.getElementById('publish-results'),",
    "  draftMeta: document.getElementById('draft-meta'),",
    "  ebaySection: document.getElementById('ebay-section'),",
    "  ebaySku: document.getElementById('ebay-sku'),",
    "  ebayImageUrls: document.getElementById('ebay-image-urls'),",
    "  ebayLocation: document.getElementById('ebay-location'),",
    "  ebayFulfillment: document.getElementById('ebay-fulfillment'),",
    "  ebayPayment: document.getElementById('ebay-payment'),",
    "  ebayReturn: document.getElementById('ebay-return'),",
    "  copyModeNote: document.getElementById('copy-mode-note'),",
    "  platformModeNote: document.getElementById('platform-mode-note'),",
    "  clearRuntimeSettings: document.getElementById('clear-runtime-settings'),",
    "  settingAnthropicAuthToken: document.getElementById('setting-anthropic-auth-token'),",
    "  settingAnthropicApiKey: document.getElementById('setting-anthropic-api-key'),",
    "  settingAnthropicBaseUrl: document.getElementById('setting-anthropic-base-url'),",
    "  settingAnthropicModel: document.getElementById('setting-anthropic-model'),",
    "  settingEbayClientId: document.getElementById('setting-ebay-client-id'),",
    "  settingEbayClientSecret: document.getElementById('setting-ebay-client-secret'),",
    "  settingEbayEnv: document.getElementById('setting-ebay-env'),",
    "  settingEbayRedirectUri: document.getElementById('setting-ebay-redirect-uri'),",
    "  settingEbayUserRefreshToken: document.getElementById('setting-ebay-user-refresh-token'),",
    "  ebayAuthCode: document.getElementById('ebay-auth-code'),",
    "  ebayAuthLink: document.getElementById('ebay-auth-link'),",
    "  ebayAuthUrlButton: document.getElementById('ebay-auth-url'),",
    "  ebayExchangeButton: document.getElementById('ebay-exchange'),",
  "};",
    "function escapeHtml(value) {",
    "  return String(value == null ? '' : value).replace(/[&<>\"']/g, function (ch) {",
    "    return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', \"'\": '&#39;' })[ch];",
    "  });",
    "}",
    "function splitLines(value) {",
    "  return String(value == null ? '' : value)",
    "    .split(/\\r?\\n|,/)",
    "    .map(function (line) { return line.trim(); })",
    "    .filter(Boolean);",
    "}",
    "function safeHttpUrl(value) {",
    "  try { var raw = String(value || ''); if (!/^https?:\\/\\//i.test(raw)) return '#'; var parsed = new URL(raw); return parsed.protocol === 'http:' || parsed.protocol === 'https:' ? parsed.href : '#'; } catch (_) { return '#'; }",
    "}",
    "function stableGuiSku(draftId, prefix) {",
    "  var safeId = String(draftId || '').replace(/[^a-zA-Z0-9]/g, '').slice(0, 32);",
    "  var safePrefix = String(prefix || '').replace(/[^a-zA-Z0-9_-]/g, '').slice(0, 12);",
    "  return ((safePrefix ? safePrefix + '-' : 'resale-gui-') + safeId).slice(0, 50);",
    "}",
    "function show(el, on) { if (el) el.hidden = !on; }",
    "function getStoredDraftId() { try { return localStorage.getItem('resell-agent.gui.draftId'); } catch (_) { return null; } }",
    "function storeDraftId(value) { try { if (value) localStorage.setItem('resell-agent.gui.draftId', value); } catch (_) {} }",
    "function clearStoredDraftId() { try { localStorage.removeItem('resell-agent.gui.draftId'); } catch (_) {} }",
    "function setStatus(message, kind) {",
    "  els.status.textContent = message;",
    "  els.status.dataset.kind = kind || 'info';",
    "}",
    "function apiFetch(path, init) {",
    "  return fetch(path, Object.assign({ credentials: 'same-origin' }, init || {}));",
    "}",
    "async function responsePayload(response) {",
    "  var text = await response.text();",
    "  try { return text ? JSON.parse(text) : {}; } catch (_) { return { error: text || 'Unexpected server response' }; }",
    "}",
    "function collectRuntimeSettings() {",
    "  var fields = [",
    "    ['ANTHROPIC_AUTH_TOKEN', els.settingAnthropicAuthToken],",
    "    ['ANTHROPIC_BASE_URL', els.settingAnthropicBaseUrl],",
    "    ['ANTHROPIC_MODEL', els.settingAnthropicModel],",
    "    ['ANTHROPIC_API_KEY', els.settingAnthropicApiKey],",
    "    ['EBAY_CLIENT_ID', els.settingEbayClientId],",
    "    ['EBAY_CLIENT_SECRET', els.settingEbayClientSecret],",
    "    ['EBAY_ENV', els.settingEbayEnv],",
    "    ['EBAY_REDIRECT_URI', els.settingEbayRedirectUri],",
    "    ['EBAY_USER_REFRESH_TOKEN', els.settingEbayUserRefreshToken],",
    "  ];",
    "  var settings = {};",
    "  fields.forEach(function (entry) { var key = entry[0]; var field = entry[1]; var value = field && typeof field.value === 'string' ? field.value.trim() : ''; if (value) settings[key] = value; });",
    "  return settings;",
    "}",
    "function updatePlatformModeNote() {",
    "  var hasEbay = selectedPlatforms().indexOf('ebay') >= 0;",
    "  if (els.platformModeNote) els.platformModeNote.textContent = hasEbay ? 'eBay pricing, comps, and publishing are enabled for this selection. Uncheck eBay for copy/paste mode without eBay credentials.' : 'Copy/paste mode: no eBay credentials or eBay active/sold comps are needed. Set a price manually and copy each listing below.';",
    "}",
    "function setCardStatus(platform, kind, message) {",
    "  if (BOOT.platforms.indexOf(platform) < 0) return;",
    "  var card = document.querySelector('[data-platform=\"' + platform + '\"]');",
    "  if (!card) return;",
    "  var status = card.querySelector('[data-status]');",
    "  if (!status) return;",
    "  status.dataset.kind = kind;",
    "  status.textContent = message;",
    "}",
    "function resultKind(value) { return ['published', 'error', 'unknown', 'skipped'].indexOf(value) >= 0 ? value : 'error'; }",
    "function resetCardStatuses() {",
    "  document.querySelectorAll('[data-status]').forEach(function (status) {",
    "    status.dataset.kind = 'idle';",
    "    status.textContent = 'Ready';",
    "  });",
    "  document.querySelectorAll('[data-copy-status]').forEach(function (status) {",
    "    status.dataset.kind = 'idle';",
    "    status.textContent = 'Not copied';",
    "  });",
    "  if (els.resultPanel) els.resultPanel.innerHTML = '';",
    "  state.publishResults = [];",
    "}",
    "function renderPublishResults(results) {",
    "  state.publishResults = Array.isArray(results) ? results : [];",
    "  els.resultPanel.innerHTML = state.publishResults.map(function (result) {",
    "    var kind = resultKind(result.status);",
    "    setCardStatus(result.platform, kind, kind === 'skipped' ? 'Already published' : kind);",
    "    return '<div class=\"result ' + kind + '\"><strong>' + escapeHtml(result.platform) + '</strong> — ' + escapeHtml(result.message) + '</div>';",
    "  }).join('');",
    "}",
    "function summaryRow(label, value) {",
    "  return '<div class=\"summary-item\"><span>' + escapeHtml(label) + '</span><strong>' + escapeHtml(value || '—') + '</strong></div>';",
    "}",
    "function renderSummary(draft) {",
    "  var a = draft.attributes || {};",
    "  var flaws = Array.isArray(a.flaws) && a.flaws.length ? a.flaws.join('; ') : '—';",
    "  var price = draft.price || {};",
    "  var comparison = Array.isArray(draft.comparison) ? draft.comparison : [];",
    "  var retail = Array.isArray(draft.retail) ? draft.retail : [];",
    "  els.summary.innerHTML = [",
    "    '<section class=\"summary-grid\">',",
    "      summaryRow('Brand', a.brand),",
    "      summaryRow('Product', a.productName),",
    "      summaryRow('Category', a.category),",
    "      summaryRow('Size', a.size),",
    "      summaryRow('Color', a.color),",
    "      summaryRow('Material', a.material),",
    "      summaryRow('Condition', a.condition),",
    "      summaryRow('Dimensions', a.dimensions),",
    "      summaryRow('Original retail', a.originalRetail == null ? '—' : '$' + a.originalRetail),",
    "      summaryRow('Flaws', flaws),",
    "    '</section>',",
    "    '<section class=\"summary-grid\">',",
    "      summaryRow('Suggested price', price.suggested ? ('$' + price.suggested) : 'Set manually'),",
    "      summaryRow('Price range', price.low ? ('$' + price.low + '–$' + price.high) : '—'),",
    "      summaryRow('Basis', price.basis),",
    "      summaryRow('Sample size', price.sampleSize == null ? '—' : String(price.sampleSize)),",
    "    '</section>',",
    "    '<section>',",
    "      '<h3>Comparison</h3>',",
    "      comparison.length ? '<table class=\"table\"><thead><tr><th>Source</th><th>Median</th><th>Range</th><th>N</th></tr></thead><tbody>' + comparison.map(function (row) {",
    "        return '<tr><td>' + escapeHtml(row.source) + '</td><td>$' + escapeHtml(row.median) + '</td><td>$' + escapeHtml(row.low) + '–$' + escapeHtml(row.high) + '</td><td>' + escapeHtml(row.n) + '</td></tr>';",
    "      }).join('') + '</tbody></table>' : '<p class=\"muted\">No platform comparison rows were found.</p>',",
    "    '</section>',",
    "    '<section>',",
    "      '<h3>Retail</h3>',",
    "      retail.length ? '<ul class=\"retail-list\">' + retail.map(function (row) {",
    "        return '<li><a href=\"' + escapeHtml(safeHttpUrl(row.url)) + '\" target=\"_blank\" rel=\"noreferrer\">' + escapeHtml(row.retailer) + '</a> — $' + escapeHtml(row.price) + ' ' + escapeHtml(row.currency) + '</li>';",
    "      }).join('') + '</ul>' : '<p class=\"muted\">No retail match found.</p>',",
    "    '</section>',",
    "  ].join('');",
    "}",
    "function renderPhotoStrip(urls) {",
    "  if (!urls.length) {",
    "    els.photoPreview.innerHTML = '<p class=\"muted\">No photos selected yet.</p>';",
    "    return;",
    "  }",
    "  els.photoPreview.innerHTML = urls.map(function (url, index) {",
    "    return '<figure class=\"thumb\"><img src=\"' + escapeHtml(url) + '\" alt=\"Photo ' + (index + 1) + '\"><figcaption>Photo ' + (index + 1) + '</figcaption></figure>';",
    "  }).join('');",
    "}",
    "function localPreviewFiles(files) {",
    "  state.localPreviewUrls.forEach(function (url) { URL.revokeObjectURL(url); });",
    "  state.localPreviewUrls = files.map(function (file) { return URL.createObjectURL(file); });",
    "  renderPhotoStrip(state.localPreviewUrls);",
    "}",
    "function renderListingCard(listing) {",
    "  var specifics = listing.itemSpecifics ? JSON.stringify(listing.itemSpecifics, null, 2) : '{}';",
    "  var categoryField = listing.platform === 'ebay' ? '<label>Category ID<input data-field=\"categoryId\" value=\"' + escapeHtml(listing.categoryId || '') + '\"></label>' : '';",
    "  var extraNote = listing.platform === 'ebay' ? '<p class=\"muted\">eBay publish still needs public image URLs and the one-time account IDs.</p>' : '<p class=\"muted\">Browser automation is optional; use Copy listing for manual copy/paste.</p>';",
    "  return '<article class=\"listing-card\" data-platform=\"' + listing.platform + '\">' +",
    "    '<header><div><h3>' + listing.platform.toUpperCase() + '</h3><p class=\"muted\">Condition: ' + escapeHtml(listing.condition || '') + '</p></div><div class=\"publish-status\" data-status data-kind=\"idle\">Ready</div></header>' +",
    "    '<label>Title<input data-field=\"title\" value=\"' + escapeHtml(listing.title) + '\"></label>' +",
    "    '<label>Description<textarea data-field=\"description\" rows=\"9\">' + escapeHtml(listing.description) + '</textarea></label>' +",
    "    '<div class=\"two-col\"><label>Price<input data-field=\"price\" type=\"number\" step=\"0.01\" value=\"' + escapeHtml(listing.price) + '\"></label>' + categoryField + '</div>' +",
    "    (listing.platform === 'ebay' ? '<details><summary>Item specifics</summary><pre>' + escapeHtml(specifics) + '</pre></details>' : '') +",
    "    '<div class=\"copy-actions\"><button class=\"secondary small\" type=\"button\" data-copy-listing>Copy listing</button><span class=\"copy-status\" data-copy-status data-kind=\"idle\">Not copied</span></div>' +",
    "    extraNote +",
    "  '</article>';",
    "}",
    "async function writeClipboardText(text) {",
    "  if (navigator.clipboard && typeof navigator.clipboard.writeText === 'function') {",
    "    try { await navigator.clipboard.writeText(text); return; } catch (_) {}",
    "  }",
    "  var area = document.createElement('textarea');",
    "  area.value = text; area.setAttribute('readonly', ''); area.style.position = 'fixed'; area.style.opacity = '0';",
    "  document.body.appendChild(area); area.select();",
    "  try { if (!document.execCommand('copy')) throw new Error('Clipboard permission was denied.'); } finally { document.body.removeChild(area); }",
    "}",
    "async function copyListing(card) {",
    "  if (!card || !state.draft) return;",
    "  var platform = card.dataset.platform || '';",
    "  var original = state.draft.listings.find(function (listing) { return listing.platform === platform; }) || {};",
    "  var title = card.querySelector('[data-field=\"title\"]');",
    "  var description = card.querySelector('[data-field=\"description\"]');",
    "  var price = card.querySelector('[data-field=\"price\"]');",
    "  var value = 'Title: ' + (title ? title.value : original.title || '') + '\\n\\n' +",
    "    'Description:\\n' + (description ? description.value : original.description || '') + '\\n\\n' +",
    "    'Price: ' + (price && price.value && Number(price.value) > 0 ? '$' + price.value : 'Set manually') + '\\n' +",
    "    'Condition: ' + (original.condition || '');",
    "  var status = card.querySelector('[data-copy-status]');",
    "  try { await writeClipboardText(value); if (status) { status.dataset.kind = 'success'; status.textContent = 'Copied'; } setStatus(platform.toUpperCase() + ' listing copied to clipboard.', 'success'); }",
    "  catch (error) { var message = String(error && error.message ? error.message : error); if (status) { status.dataset.kind = 'error'; status.textContent = 'Copy failed'; } setStatus('Could not copy the ' + platform.toUpperCase() + ' listing: ' + message, 'error'); }",
    "}",
    "function attachEditListeners() {",
    "  els.listingCards.querySelectorAll('[data-field]').forEach(function (input) { input.addEventListener('input', queueDraftSave); });",
    "  ['ebay-image-urls', 'ebay-location', 'ebay-fulfillment', 'ebay-payment', 'ebay-return'].forEach(function (id) { var input = document.getElementById(id); if (input) input.addEventListener('input', queueDraftSave); });",
    "  els.listingCards.querySelectorAll('[data-copy-listing]').forEach(function (button) { button.addEventListener('click', function () { copyListing(button.closest('[data-platform]')); }); });",
    "}",
    "function renderDraft(data) {",
    "  if (state.saveTimer) { clearTimeout(state.saveTimer); state.saveTimer = null; }",
    "  state.draftId = data.draftId || null;",
    "  state.draft = data.draft || null;",
    "  state.serverPreviewUrls = Array.isArray(data.photos) ? data.photos.map(function (p) { return p.url; }) : [];",
    "  if (state.draftId) storeDraftId(state.draftId);",
    "  if (state.localPreviewUrls.length) {",
    "    state.localPreviewUrls.forEach(function (url) { URL.revokeObjectURL(url); });",
    "    state.localPreviewUrls = [];",
    "  }",
    "  show(els.publishPanel, true);",
    "  show(els.draftMeta, true);",
    "  els.draftMeta.textContent = 'Draft ' + state.draftId + ' is ready. Edits are saved locally on the server.';",
    "  renderSummary(state.draft);",
    "  els.listingCards.innerHTML = state.draft.listings.map(renderListingCard).join('');",
    "  els.platformInputs.forEach(function (input) { input.checked = state.draft.listings.some(function (listing) { return listing.platform === input.value; }); });",
    "  attachEditListeners();",
    "  renderPhotoStrip(state.serverPreviewUrls);",
    "  var hasEbay = state.draft.listings.some(function (listing) { return listing.platform === 'ebay'; });",
    "  show(els.ebaySection, hasEbay);",
    "  show(els.copyModeNote, !hasEbay);",
    "  var ebay = data.ebay || {};",
    "  if (hasEbay) {",
    "    els.ebaySku.value = stableGuiSku(state.draftId, data.guiSkuPrefix || BOOT.ebayDefaults.sku);",
    "    els.ebayLocation.value = ebay.merchantLocationKey || BOOT.ebayDefaults.merchantLocationKey || '';",
    "    els.ebayFulfillment.value = ebay.fulfillmentPolicyId || BOOT.ebayDefaults.fulfillmentPolicyId || '';",
    "    els.ebayPayment.value = ebay.paymentPolicyId || BOOT.ebayDefaults.paymentPolicyId || '';",
    "    els.ebayReturn.value = ebay.returnPolicyId || BOOT.ebayDefaults.returnPolicyId || '';",
    "    els.ebayImageUrls.value = Array.isArray(ebay.imageUrls) ? ebay.imageUrls.join('\\n') : '';",
    "  }",
    "  renderPublishResults(data.publishResults || []);",
    "  updatePlatformModeNote();",
    "}",
    "function collectEditableEdits() {",
    "  if (!state.draft) throw new Error('No draft to publish yet.');",
    "  return state.draft.listings.map(function (listing) {",
    "    var card = document.querySelector('[data-platform=\"' + listing.platform + '\"]');",
    "    if (!card) return { platform: listing.platform };",
    "    var title = card.querySelector('[data-field=\"title\"]');",
    "    var description = card.querySelector('[data-field=\"description\"]');",
    "    var price = card.querySelector('[data-field=\"price\"]');",
    "    var category = card.querySelector('[data-field=\"categoryId\"]');",
    "    var patch = { platform: listing.platform, title: title ? title.value : listing.title, description: description ? description.value : listing.description, price: price ? Number(price.value) : listing.price };",
    "    if (listing.platform === 'ebay' && category && category.value.trim()) patch.categoryId = category.value;",
    "    return patch;",
    "  });",
    "}",
    "function collectEbaySettings() {",
    "  return { sku: els.ebaySku.value.trim(), imageUrls: splitLines(els.ebayImageUrls.value), merchantLocationKey: els.ebayLocation.value.trim(), fulfillmentPolicyId: els.ebayFulfillment.value.trim(), paymentPolicyId: els.ebayPayment.value.trim(), returnPolicyId: els.ebayReturn.value.trim() };",
    "}",
    "async function saveDraftEdits() {",
    "  if (!state.draftId || !state.draft) return;",
    "  var patch = { edits: collectEditableEdits() };",
    "  if (state.draft.listings.some(function (listing) { return listing.platform === 'ebay'; })) patch.ebay = collectEbaySettings();",
    "  var response = await apiFetch('/api/draft/' + encodeURIComponent(state.draftId), { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(patch) });",
    "  var payload = await responsePayload(response);",
    "  if (!response.ok) throw new Error(payload.error || 'Could not save draft edits');",
    "  state.draft = payload.draft || state.draft;",
    "}",
    "function queueDraftSave() {",
    "  if (state.saveTimer) clearTimeout(state.saveTimer);",
    "  state.saveTimer = setTimeout(function () { saveDraftEdits().catch(function (error) { setStatus(String(error && error.message ? error.message : error), 'error'); }); }, 450);",
    "}",
    "function selectedPlatforms() {",
    "  return BOOT.platforms.filter(function (platform) { return document.querySelector('input[name=\"platforms\"][value=\"' + platform + '\"]:checked'); });",
    "}",
    "async function buildDraft(event) {",
    "  event.preventDefault();",
    "  if (!els.photoInput.files || !els.photoInput.files.length) {",
    "    setStatus('Choose at least one photo before building a draft.', 'error');",
    "    return;",
    "  }",
    "  if (!selectedPlatforms().length) { setStatus('Select at least one platform before building a draft.', 'error'); return; }",
    "  setStatus('Building draft...', 'info');",
    "  els.buildButton.disabled = true;",
    "  els.publishButton.disabled = true;",
    "  try {",
    "    var formData = new FormData(els.form);",
    "    formData.set('settings', JSON.stringify(collectRuntimeSettings()));",
    "    var response = await apiFetch('/api/draft', { method: 'POST', body: formData });",
    "    var payload = await responsePayload(response);",
    "    if (!response.ok) throw new Error(payload.error || payload.message || 'Draft build failed');",
    "    renderDraft(payload);",
    "    resetCardStatuses();",
    "    setStatus(state.draft && state.draft.listings.some(function (listing) { return listing.platform === 'ebay'; }) ? 'Draft ready. Review the copy, then publish.' : 'Draft ready in copy/paste mode. Review, set prices manually if needed, and copy each listing.', 'success');",
    "    els.publishButton.disabled = false;",
    "  } catch (error) {",
    "    setStatus(String(error && error.message ? error.message : error), 'error');",
    "  } finally {",
    "    els.buildButton.disabled = false;",
    "  }",
    "}",
    "async function publishAll() {",
    "  if (!state.draftId || !state.draft) { setStatus('Build a draft first.', 'error'); return; }",
    "  var platforms = selectedPlatforms();",
    "  if (!platforms.length) { setStatus('Select at least one platform to publish.', 'error'); return; }",
    "  setStatus('Saving edits and publishing...', 'info');",
    "  els.publishButton.disabled = true;",
    "  try {",
    "    var edits = collectEditableEdits();",
    "    await saveDraftEdits();",
    "    var body = {",
      "      draftId: state.draftId,",
      "      edits: edits,",
      "      platforms: platforms,",
      "      settings: collectRuntimeSettings(),",
    "    };",
    "    if (platforms.indexOf('ebay') >= 0) body.ebay = collectEbaySettings();",
    "    var response = await apiFetch('/api/publish', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });",
    "    var payload = await responsePayload(response);",
    "    if (!response.ok) throw new Error(payload.error || payload.message || 'Publish failed');",
    "    renderPublishResults(payload.results);",
    "    var failures = payload.results.filter(function (result) { return result.status === 'error' || result.status === 'unknown'; });",
    "    var successes = payload.results.filter(function (result) { return result.status === 'published' || result.status === 'skipped'; });",
    "    if (!failures.length) setStatus(successes.some(function (result) { return result.status === 'skipped'; }) ? 'All selected targets were already published; no duplicate retry was made.' : 'All selected platforms published successfully.', 'success');",
    "    else if (successes.length) setStatus('Some platforms completed, but one or more targets failed or have an unknown status. Review each result before retrying.', 'info');",
    "    else setStatus('No selected platform was confirmed successful. Unknown results may still have published; verify before retrying.', 'error');",
    "  } catch (error) {",
    "    setStatus(String(error && error.message ? error.message : error), 'error');",
    "  } finally {",
    "    els.publishButton.disabled = false;",
    "  }",
    "}",
    "function updateSelectedPhotos() {",
    "  var files = els.photoInput.files ? Array.from(els.photoInput.files) : [];",
    "  localPreviewFiles(files);",
    "  if (files.length) setStatus('Selected ' + files.length + ' photo(s).', 'info');",
    "}",
    "async function clearRuntimeSettings() {",
    "  if (els.clearRuntimeSettings) els.clearRuntimeSettings.disabled = true;",
    "  try {",
    "    var response = await apiFetch('/api/settings/clear', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' });",
    "    var payload = await responsePayload(response);",
    "    if (!response.ok) throw new Error(payload.error || 'Could not clear runtime settings');",
    "    [els.settingAnthropicAuthToken, els.settingAnthropicApiKey, els.settingAnthropicBaseUrl, els.settingAnthropicModel, els.settingEbayClientId, els.settingEbayClientSecret, els.settingEbayEnv, els.settingEbayRedirectUri, els.settingEbayUserRefreshToken].forEach(function (field) { if (field) field.value = ''; });",
    "    setStatus('Runtime settings cleared; process-start values will be used again.', 'success');",
    "  } catch (error) { setStatus(String(error && error.message ? error.message : error), 'error'); }",
    "  finally { if (els.clearRuntimeSettings) els.clearRuntimeSettings.disabled = false; }",
    "}",
    "async function getEbayAuthUrl() {",
    "  if (els.ebayAuthUrlButton) els.ebayAuthUrlButton.disabled = true;",
    "  try {",
    "    var response = await apiFetch('/api/ebay/auth-url', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ settings: collectRuntimeSettings() }) });",
    "    var payload = await responsePayload(response);",
    "    if (!response.ok) throw new Error(payload.error || 'Could not create the eBay sign-in link');",
    "    if (els.ebayAuthLink) { els.ebayAuthLink.href = payload.url; els.ebayAuthLink.hidden = false; }",
    "    setStatus('eBay sign-in link ready. Open it, approve access, then paste the returned code below.', 'success');",
    "  } catch (error) { setStatus(String(error && error.message ? error.message : error), 'error'); }",
    "  finally { if (els.ebayAuthUrlButton) els.ebayAuthUrlButton.disabled = false; }",
    "}",
    "async function exchangeEbayCode() {",
    "  var code = els.ebayAuthCode && els.ebayAuthCode.value ? els.ebayAuthCode.value.trim() : '';",
    "  if (!code) { setStatus('Paste the eBay authorization code first.', 'error'); return; }",
    "  if (els.ebayExchangeButton) els.ebayExchangeButton.disabled = true;",
    "  try {",
    "    var response = await apiFetch('/api/ebay/exchange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code: code, settings: collectRuntimeSettings() }) });",
    "    var payload = await responsePayload(response);",
    "    if (!response.ok) throw new Error(payload.error || 'Could not exchange the eBay code');",
    "    if (els.settingEbayUserRefreshToken) els.settingEbayUserRefreshToken.value = payload.refreshToken || '';",
    "    if (els.ebayAuthCode) els.ebayAuthCode.value = '';",
    "    setStatus('eBay refresh token received in memory. It will be used for this GUI process and is not saved to disk.', 'success');",
    "  } catch (error) { setStatus(String(error && error.message ? error.message : error), 'error'); }",
    "  finally { if (els.ebayExchangeButton) els.ebayExchangeButton.disabled = false; }",
    "}",
    "async function recoverDraft() {",
    "  var draftId = getStoredDraftId();",
    "  if (!draftId) return;",
    "  setStatus('Recovering saved draft...', 'info');",
    "  try {",
    "    var response = await apiFetch('/api/draft/' + encodeURIComponent(draftId));",
    "    var payload = await responsePayload(response);",
    "    if (response.status === 404) { clearStoredDraftId(); setStatus('Saved draft expired; choose photos to begin.', 'info'); return; }",
    "    if (!response.ok) throw new Error(payload.error || 'Could not recover draft');",
    "    renderDraft(payload);",
    "    els.publishButton.disabled = false;",
    "    setStatus('Recovered draft ' + draftId + '. Review the saved edits before publishing.', 'success');",
    "  } catch (error) { setStatus(String(error && error.message ? error.message : error), 'error'); }",
    "}",
    "els.form.addEventListener('submit', buildDraft);",
    "els.photoInput.addEventListener('change', updateSelectedPhotos);",
    "els.platformInputs.forEach(function (input) { input.addEventListener('change', updatePlatformModeNote); });",
    "if (els.clearRuntimeSettings) els.clearRuntimeSettings.addEventListener('click', clearRuntimeSettings);",
    "if (els.ebayAuthUrlButton) els.ebayAuthUrlButton.addEventListener('click', getEbayAuthUrl);",
    "if (els.ebayExchangeButton) els.ebayExchangeButton.addEventListener('click', exchangeEbayCode);",
    "els.publishButton.addEventListener('click', function (event) { event.preventDefault(); publishAll(); });",
    "setStatus(BOOT.browserAutomationEnabled ? 'Browser automation is enabled when configured.' : 'Browser automation is disabled until ENABLE_BROWSER_AUTOMATION=1 is set.', 'info');",
    "renderPhotoStrip([]);",
    "updatePlatformModeNote();",
    "show(els.publishPanel, false);",
    "recoverDraft();",
  ];

  return lines.join("\n");
}
