import type { Platform } from "./types.js";

export interface GuiBootState {
  platforms: Platform[];
  browserAutomationEnabled: boolean;
  ebayDefaults: {
    sku: string;
    merchantLocationKey: string;
    fulfillmentPolicyId: string;
    paymentPolicyId: string;
    returnPolicyId: string;
  };
}

function escapeJsonForScript(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}

export function buildGuiScript(boot: GuiBootState): string {
  const lines: string[] = [
    `const BOOT = ${escapeJsonForScript(boot)};`,
    "const state = { draftId: null, draft: null, localPreviewUrls: [], serverPreviewUrls: [] };",
    "const els = {",
    "  form: document.getElementById('draft-form'),",
    "  photoInput: document.getElementById('photos'),",
    "  noteInput: document.getElementById('notes'),",
    "  referenceInput: document.getElementById('referenceImageUrl'),",
    "  platformInputs: Array.from(document.querySelectorAll('input[name=\"platforms\"]')),",
    "  buildButton: document.getElementById('build-draft'),",
    "  publishButton: document.getElementById('publish-all'),",
    "  status: document.getElementById('global-status'),",
    "  summary: document.getElementById('summary'),",
    "  photoPreview: document.getElementById('photo-preview'),",
    "  listingCards: document.getElementById('listing-cards'),",
    "  publishPanel: document.getElementById('publish-panel'),",
    "  resultPanel: document.getElementById('publish-results'),",
    "  draftMeta: document.getElementById('draft-meta'),",
    "  ebaySection: document.getElementById('ebay-section'),",
    "  ebaySku: document.getElementById('ebay-sku'),",
    "  ebayImageUrls: document.getElementById('ebay-image-urls'),",
    "  ebayLocation: document.getElementById('ebay-location'),",
    "  ebayFulfillment: document.getElementById('ebay-fulfillment'),",
    "  ebayPayment: document.getElementById('ebay-payment'),",
    "  ebayReturn: document.getElementById('ebay-return'),",
    "};",
    "function escapeHtml(value) {",
    "  return String(value == null ? '' : value).replace(/[&<>\"']/g, function (ch) {",
    "    return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', \"'\": '&#39;' })[ch];",
    "  });",
    "}",
    "function splitLines(value) {",
    "  return String(value == null ? '' : value)",
    "    .split(/\\r?\\n|,/)",
    "    .map(function (line) { return line.trim(); })",
    "    .filter(Boolean);",
    "}",
    "function show(el, on) { if (el) el.hidden = !on; }",
    "function setStatus(message, kind) {",
    "  els.status.textContent = message;",
    "  els.status.dataset.kind = kind || 'info';",
    "}",
    "function setCardStatus(platform, kind, message) {",
    "  var card = document.querySelector('[data-platform=\"' + platform + '\"]');",
    "  if (!card) return;",
    "  var status = card.querySelector('[data-status]');",
    "  if (!status) return;",
    "  status.dataset.kind = kind;",
    "  status.textContent = message;",
    "}",
    "function resetCardStatuses() {",
    "  document.querySelectorAll('[data-status]').forEach(function (status) {",
    "    status.dataset.kind = 'idle';",
    "    status.textContent = 'Ready';",
    "  });",
    "  if (els.resultPanel) els.resultPanel.innerHTML = '';",
    "}",
    "function summaryRow(label, value) {",
    "  return '<div class=\"summary-item\"><span>' + escapeHtml(label) + '</span><strong>' + escapeHtml(value || '—') + '</strong></div>';",
    "}",
    "function renderSummary(draft) {",
    "  var a = draft.attributes || {};",
    "  var flaws = Array.isArray(a.flaws) && a.flaws.length ? a.flaws.join('; ') : '—';",
    "  var price = draft.price || {};",
    "  var comparison = Array.isArray(draft.comparison) ? draft.comparison : [];",
    "  var retail = Array.isArray(draft.retail) ? draft.retail : [];",
    "  els.summary.innerHTML = [",
    "    '<section class=\"summary-grid\">',",
    "      summaryRow('Brand', a.brand),",
    "      summaryRow('Product', a.productName),",
    "      summaryRow('Category', a.category),",
    "      summaryRow('Size', a.size),",
    "      summaryRow('Color', a.color),",
    "      summaryRow('Material', a.material),",
    "      summaryRow('Condition', a.condition),",
    "      summaryRow('Dimensions', a.dimensions),",
    "      summaryRow('Original retail', a.originalRetail == null ? '—' : '$' + a.originalRetail),",
    "      summaryRow('Flaws', flaws),",
    "    '</section>',",
    "    '<section class=\"summary-grid\">',",
    "      summaryRow('Suggested price', price.suggested ? ('$' + price.suggested) : 'Set manually'),",
    "      summaryRow('Price range', price.low ? ('$' + price.low + '–$' + price.high) : '—'),",
    "      summaryRow('Basis', price.basis),",
    "      summaryRow('Sample size', price.sampleSize == null ? '—' : String(price.sampleSize)),",
    "    '</section>',",
    "    '<section>',",
    "      '<h3>Comparison</h3>',",
    "      comparison.length ? '<table class=\"table\"><thead><tr><th>Source</th><th>Median</th><th>Range</th><th>N</th></tr></thead><tbody>' + comparison.map(function (row) {",
    "        return '<tr><td>' + escapeHtml(row.source) + '</td><td>$' + escapeHtml(row.median) + '</td><td>$' + escapeHtml(row.low) + '–$' + escapeHtml(row.high) + '</td><td>' + escapeHtml(row.n) + '</td></tr>';",
    "      }).join('') + '</tbody></table>' : '<p class=\"muted\">No platform comparison rows were found.</p>',",
    "    '</section>',",
    "    '<section>',",
    "      '<h3>Retail</h3>',",
    "      retail.length ? '<ul class=\"retail-list\">' + retail.map(function (row) {",
    "        return '<li><a href=\"' + escapeHtml(row.url) + '\" target=\"_blank\" rel=\"noreferrer\">' + escapeHtml(row.retailer) + '</a> — $' + escapeHtml(row.price) + ' ' + escapeHtml(row.currency) + '</li>';",
    "      }).join('') + '</ul>' : '<p class=\"muted\">No retail match found.</p>',",
    "    '</section>',",
    "  ].join('');",
    "}",
    "function renderPhotoStrip(urls) {",
    "  if (!urls.length) {",
    "    els.photoPreview.innerHTML = '<p class=\"muted\">No photos selected yet.</p>';",
    "    return;",
    "  }",
    "  els.photoPreview.innerHTML = urls.map(function (url, index) {",
    "    return '<figure class=\"thumb\"><img src=\"' + escapeHtml(url) + '\" alt=\"Photo ' + (index + 1) + '\"><figcaption>Photo ' + (index + 1) + '</figcaption></figure>';",
    "  }).join('');",
    "}",
    "function localPreviewFiles(files) {",
    "  state.localPreviewUrls.forEach(function (url) { URL.revokeObjectURL(url); });",
    "  state.localPreviewUrls = files.map(function (file) { return URL.createObjectURL(file); });",
    "  renderPhotoStrip(state.localPreviewUrls);",
    "}",
    "function renderListingCard(listing) {",
    "  var specifics = listing.itemSpecifics ? JSON.stringify(listing.itemSpecifics, null, 2) : '{}';",
    "  var categoryField = listing.platform === 'ebay' ? '<label>Category ID<input data-field=\"categoryId\" value=\"' + escapeHtml(listing.categoryId || '') + '\"></label>' : '';",
    "  var extraNote = listing.platform === 'ebay' ? '<p class=\"muted\">eBay publish still needs public image URLs and the one-time account IDs.</p>' : '<p class=\"muted\">Browser automation is optional and must be configured per platform.</p>';",
    "  return '<article class=\"listing-card\" data-platform=\"' + listing.platform + '\">' +",
    "    '<header><div><h3>' + listing.platform.toUpperCase() + '</h3><p class=\"muted\">Condition: ' + escapeHtml(listing.condition || '') + '</p></div><div class=\"publish-status\" data-status data-kind=\"idle\">Ready</div></header>' +",
    "    '<label>Title<input data-field=\"title\" value=\"' + escapeHtml(listing.title) + '\"></label>' +",
    "    '<label>Description<textarea data-field=\"description\" rows=\"9\">' + escapeHtml(listing.description) + '</textarea></label>' +",
    "    '<div class=\"two-col\"><label>Price<input data-field=\"price\" type=\"number\" step=\"0.01\" value=\"' + escapeHtml(listing.price) + '\"></label>' + categoryField + '</div>' +",
    "    (listing.platform === 'ebay' ? '<details><summary>Item specifics</summary><pre>' + escapeHtml(specifics) + '</pre></details>' : '') +",
    "    extraNote +",
    "  '</article>';",
    "}",
    "function renderDraft(data) {",
    "  state.draftId = data.draftId || null;",
    "  state.draft = data.draft || null;",
    "  state.serverPreviewUrls = Array.isArray(data.photos) ? data.photos.map(function (p) { return p.url; }) : [];",
    "  if (state.localPreviewUrls.length) {",
    "    state.localPreviewUrls.forEach(function (url) { URL.revokeObjectURL(url); });",
    "    state.localPreviewUrls = [];",
    "  }",
    "  show(els.publishPanel, true);",
    "  show(els.draftMeta, true);",
    "  els.draftMeta.textContent = 'Draft ' + state.draftId + ' is ready. Edit copy before publishing.';",
    "  renderSummary(state.draft);",
    "  els.listingCards.innerHTML = state.draft.listings.map(renderListingCard).join('');",
    "  renderPhotoStrip(state.serverPreviewUrls);",
    "  var hasEbay = state.draft.listings.some(function (listing) { return listing.platform === 'ebay'; });",
    "  show(els.ebaySection, hasEbay);",
    "  if (hasEbay) {",
    "    els.ebaySku.value = BOOT.ebayDefaults.sku || ('resale-' + Date.now());",
    "    els.ebayLocation.value = BOOT.ebayDefaults.merchantLocationKey || '';",
    "    els.ebayFulfillment.value = BOOT.ebayDefaults.fulfillmentPolicyId || '';",
    "    els.ebayPayment.value = BOOT.ebayDefaults.paymentPolicyId || '';",
    "    els.ebayReturn.value = BOOT.ebayDefaults.returnPolicyId || '';",
    "  }",
    "}",
    "function collectDraftEdits() {",
    "  if (!state.draft) throw new Error('No draft to publish yet.');",
    "  var draft = JSON.parse(JSON.stringify(state.draft));",
    "  draft.listings.forEach(function (listing) {",
    "    var card = document.querySelector('[data-platform=\"' + listing.platform + '\"]');",
    "    if (!card) return;",
    "    var title = card.querySelector('[data-field=\"title\"]');",
    "    var description = card.querySelector('[data-field=\"description\"]');",
    "    var price = card.querySelector('[data-field=\"price\"]');",
    "    var category = card.querySelector('[data-field=\"categoryId\"]');",
    "    listing.title = title ? title.value.trim() : listing.title;",
    "    listing.description = description ? description.value.trim() : listing.description;",
    "    listing.price = price ? Number(price.value) : listing.price;",
    "    if (listing.platform === 'ebay' && category) listing.categoryId = category.value.trim();",
    "  });",
    "  return draft;",
    "}",
    "function selectedPlatforms() {",
    "  return BOOT.platforms.filter(function (platform) {",
    "    return document.querySelector('input[name=\"platforms\"][value=\"' + platform + '\"]:checked');",
    "  });",
    "}",
    "async function buildDraft(event) {",
    "  event.preventDefault();",
    "  if (!els.photoInput.files || !els.photoInput.files.length) {",
    "    setStatus('Choose at least one photo before building a draft.', 'error');",
    "    return;",
    "  }",
    "  setStatus('Building draft...', 'info');",
    "  els.buildButton.disabled = true;",
    "  els.publishButton.disabled = true;",
    "  try {",
    "    var response = await fetch('/api/draft', { method: 'POST', body: new FormData(els.form) });",
    "    var payload = await response.json();",
    "    if (!response.ok) throw new Error(payload.error || payload.message || 'Draft build failed');",
    "    renderDraft(payload);",
    "    resetCardStatuses();",
    "    setStatus('Draft ready. Review the copy, then publish.', 'success');",
    "    els.publishButton.disabled = false;",
    "  } catch (error) {",
    "    setStatus(String(error && error.message ? error.message : error), 'error');",
    "  } finally {",
    "    els.buildButton.disabled = false;",
    "  }",
    "}",
    "async function publishAll() {",
    "  if (!state.draftId || !state.draft) {",
    "    setStatus('Build a draft first.', 'error');",
    "    return;",
    "  }",
    "  setStatus('Publishing...', 'info');",
    "  els.publishButton.disabled = true;",
    "  try {",
    "    var draft = collectDraftEdits();",
    "    var body = {",
    "      draftId: state.draftId,",
    "      draft: draft,",
    "      platforms: selectedPlatforms(),",
    "      ebay: {",
    "        sku: els.ebaySku.value.trim(),",
    "        imageUrls: splitLines(els.ebayImageUrls.value),",
    "        merchantLocationKey: els.ebayLocation.value.trim(),",
    "        fulfillmentPolicyId: els.ebayFulfillment.value.trim(),",
    "        paymentPolicyId: els.ebayPayment.value.trim(),",
    "        returnPolicyId: els.ebayReturn.value.trim(),",
    "      },",
    "    };",
    "    var response = await fetch('/api/publish', {",
    "      method: 'POST',",
    "      headers: { 'Content-Type': 'application/json' },",
    "      body: JSON.stringify(body),",
    "    });",
    "    var payload = await response.json();",
    "    if (!response.ok) throw new Error(payload.error || payload.message || 'Publish failed');",
    "    els.resultPanel.innerHTML = payload.results.map(function (result) {",
    "      setCardStatus(result.platform, result.status, result.message);",
    "      return '<div class=\"result ' + result.status + '\"><strong>' + escapeHtml(result.platform) + '</strong> — ' + escapeHtml(result.message) + '</div>';",
    "    }).join('');",
    "    setStatus('Publish complete.', 'success');",
    "  } catch (error) {",
    "    setStatus(String(error && error.message ? error.message : error), 'error');",
    "  } finally {",
    "    els.publishButton.disabled = false;",
    "  }",
    "}",
    "function updateSelectedPhotos() {",
    "  var files = els.photoInput.files ? Array.from(els.photoInput.files) : [];",
    "  localPreviewFiles(files);",
    "  if (files.length) {",
    "    setStatus('Selected ' + files.length + ' photo(s).', 'info');",
    "  }",
    "}",
    "els.form.addEventListener('submit', buildDraft);",
    "els.photoInput.addEventListener('change', updateSelectedPhotos);",
    "els.publishButton.addEventListener('click', function (event) { event.preventDefault(); publishAll(); });",
    "setStatus(BOOT.browserAutomationEnabled ? 'Browser automation is enabled when configured.' : 'Browser automation is disabled until ENABLE_BROWSER_AUTOMATION=1 is set.', 'info');",
    "renderPhotoStrip([]);",
    "show(els.publishPanel, false);",
  ];

  return lines.join("\n");
}
